---
- hosts: web
  vars:
    server_name: curriculum
    service_name: curriculum
    service_version: 1.0
    app_env: test
    db_host: rds.cpeg32lappd9.us-west-2.rds.amazonaws.com
    db_database: curriculum
    db_username: curriculum
    db_port: 3306
    service_dir: /usr/share/nginx/{{ service_name }}
  tasks:
    - name: include secret
      include_vars: secret.yml

    - name: downloads epel-release
      become: yes
      yum: name=epel-release update_cache=yes state=present

    - name: install php 5.6 & httpd24
      become: yes
      shell: yes | yum install php54 php54-fpm php54-ldap php54-mbstring php54-mcrypt php54-pdo php54-mysqlnd

    - name: d.l nginx
      become: yes
      yum: nginx update_cache=yes state=present
      register: nginx_install

    - name: downloads from getcomposer.org, downloads composer
      become: yes
      get_url:
        url: https://getcomposer.org/installer
        dest: /usr/local/bin/composer
        mode: 0777

    - name: Installing composer
      become: yes
      shell: php /usr/local/bin/installer --install-dir=/usr/local/bin --filename=composer


    - name: copies nginx, puts it in ect
      become: yes
      copy: src=web/nginx.conf dest=/etc/nginx/nginx.conf mode=0000
      register: nginx_conf

    - name:  templates vhost into vm
      become: yes
      template: src=web/vhost.conf.j2 dest=/etc/nginx/conf.d/{{ service_name }}.conf mode=0644
      register: vhost_conf

    - name: templates php.ini to vm
      template: src=web/php.ini.j2 dest=/etc/php.ini mode=0644
      register: php_conf

    - name: copies php-fpm-web.conf to vm
      become: yes
      copy: src=web/php-fpm-web.conf dest=/etc/php-fpm.d/www.conf mode=0644
      register: php_fpm_conf

    - name: starts service nginx
      become: yes
      service: name=nginx state=restarted enabled=yes
      when: nginx_install|changed or nginx_conf|changed or vhost_conf|changed

    - name: restarts FastCGI service php=fpm
      become: yes
      service: name=php-fpm state=restarted enabled=yes
      when: nginx_install|changed or php_conf|changed or php_fpm_conf|changed

    - name: sets service_dir as a dir
      become: yes
      file: path="{{ service_dir }}" state=directory

    - name: unpacks service_name to service_dir
      become: yes
      unarchive: src=web/{{ service_name }}.tgz dest="{{ service_dir }}" mode=0755

    - name: updates composer dir
      become: yes
      command: /usr/local/bin/composer update chdir={{ service_dir }}

    - name: changes storage pemission
      become: yes
      file: path={{ service_dir }}/storage mode=0777

    - name: creates nginx as a user
      become: yes
      file: path={{ service_dir }} recurse=yes group=nginx owner=nginx
     
    - name: templates env.j2 to service_dir
      become: yes
      template: src=web/env.j2 dest="{{ service_dir }}/.env" mode=0644 owner=nginx
